### ISSUE TITLE
Usage with a layer based architecture

### ISSUE THREAD

**Issue by Kheuval** [prisma/nuxt-prisma#16]
Hello !

So I tried to move from the standard way of adding Prisma to a project as documented [here](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/introduction) (which works perfectly fine), to this module.

My project is structured like this :

├── ...
├── public
├── src     **<--- my layers folder**
│   ├── ...
│   ├── Core
│   │   ├── ...
│   │   ├── nuxt.config.ts
│   │   ├── prisma
│   │   │   └── schema.prisma     **<--- my schema is located here**
│   │   ├── ...
│   │
│   ├── ...
├── package.json
└── ...

With the standard way, I just needed to specify the path to my schema in the package.json like so : 
```json
  "prisma": {
    "schema": "src/Core/prisma/schema.prisma"
  }
```

But now it doesn't seem to work anymore, whenever I run `pnpm run dev` it creates a new `prisma` folder at the root of the project and adds the demo schema as shown in the docs.

Is there a way to use this module with this kind of folder structure ?

**Comment by ankur-arch** [comment]
Hey there @Kheuval 👋 , thanks for taking the time and creating the issue. This would be a feature request as it would require some changes as to how we generate the Prisma client.

**Comment by Kheuval** [comment]
Ok thank you for your answer :)

I will try to make a PR to be able to specify the path to the schema in the module configuration.

**Comment by ankur-arch** [comment]
Hey @Kheuval, do you have a repo where I could test and see whether I can create a workaround?

**Comment by Aguix** [comment]
Hey !

**Comment by Aguix** [comment]
Hey !
So I had this issue too (https://github.com/prisma/nuxt-prisma/issues/43) and I worked on a fix.

At the start, I did the fix directly by do the changes in the 'MyTestProject\node_modules\@prisma\nuxt' folder to be able to test in my project.
When my fix was good I did the same changes in a fork of the nuxt-prisma repo (https://github.com/Aguix/nuxt-prisma) to be able to push it and make a pull request.

My problem now is how I am supposed to include my custom nuxt-prisma module in another project for testing it?

**Comment by ankur-arch** [comment]
> My problem now is how I am supposed to include my custom nuxt-prisma module in another project for testing it? Because I think that make the change directly in the 'node_modules@prisma\nuxt' folder isn't a good way to do.

Thanks for the details @Aguix!
You can use sth like [this](https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e) and create a PR to this repo.

**Comment by Aguix** [comment]
> > My problem now is how I am supposed to include my custom nuxt-prisma module in another project for testing it? Because I think that make the change directly in the 'node_modules@prisma\nuxt' folder isn't a good way to do.
> 
> Thanks for the details @Aguix! You can use sth like [this](https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e) and create a PR to this repo.

Hello
I can't build the module.
When I do the `npm run prepack` command it says it can't read the nuxt-prisma/.nuxt/tsconfig.json file. In fact this file and even the .nuxt folder do not exist.
This is because of the nuxt-prisma/tsconfig.json file extend nuxt-prisma/.nuxt/tsconfig.json.

How I am supposed to create the .nuxt folder ?

![image](https://github.com/user-attachments/assets/6f6abf69-9e48-43cc-ae3d-ca1d196f0b59)
```error TS5083: Cannot read file 'C:/Users/.../.../nuxt-prisma/.nuxt/tsconfig.json'.```

**Comment by Aguix** [comment]
> > My problem now is how I am supposed to include my custom nuxt-prisma module in another project for testing it? Because I think that make the change directly in the 'node_modules@prisma\nuxt' folder isn't a good way to do.
> 
> Thanks for the details @Aguix! You can use sth like [this](https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e) and create a PR to this repo.

Hello back @ankur-arch 

I can't build the module.
When I do the `npm run prepack` command it says it can't read the nuxt-prisma/.nuxt/tsconfig.json file. In fact this file and even the .nuxt folder do not exist.
This is because of the nuxt-prisma/tsconfig.json file extend nuxt-prisma/.nuxt/tsconfig.json.

How I am supposed to create the .nuxt folder ?

![image](https://github.com/user-attachments/assets/6f6abf69-9e48-43cc-ae3d-ca1d196f0b59)
```error TS5083: Cannot read file 'C:/Users/.../.../nuxt-prisma/.nuxt/tsconfig.json'.```

**Comment by ankur-arch** [comment]
Hey @Aguix 👋,

Apologies for the delay! I’ve worked on a [PR](https://github.com/prisma/nuxt-prisma/pull/71) to support Nuxt layers, which has now been merged. The new `v2.0` release introduces support for a layered-based architecture with Nuxt! 

However, the docs [PR](https://github.com/prisma/docs/pull/6557) still awaiting an internal review and then merging.

> How do I create the `.nuxt` folder?

To generate and build the project, refer to the [GitHub Action workflow](https://github.com/prisma/nuxt-prisma/blob/main/.github/workflows/publish.yml#L29). 

I’ll also be working on creating a more detailed CONTRIBUTION guide for this soon.

**Comment by ankur-arch** [comment]
Closed with https://github.com/prisma/nuxt-prisma/pull/71 in v0.2. 

Look at the two new config options `prismaRoot` and `prismaSchemaPath` in the [docs](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#configuration).
