### ISSUE TITLE
Clarify usage options

### ISSUE THREAD

**Issue by david-mears-2** [prisma/nuxt-prisma#21]
In the [docs](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#usage), you demonstrate options A and B (where A is with usePrismaClient composable, and B is with "a global instance of Prisma Client"). It's not to clear to me what the difference (except syntactically) between these two options is. Is the composable just a wrapper for the global instance? If not, should we delete lib/prisma.ts?

**Comment by ankur-arch** [comment]
The additional option allows you to customize your Prisma client from a central place 👇 . 

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/c69864c9-2a5d-4833-87b6-a1ad258f4e7b">.

I'll create a PR to explain this further in the docs.

**Comment by ankur-arch** [comment]
@david-mears-2 I added a clarification in the docs via a note.
