### ISSUE TITLE
Running 'nuxt build' when '@prisma/nuxt' is listed in the modules in nuxt.config deletes other nuxt modules

### ISSUE THREAD

**Issue by david-mears-2** [prisma/nuxt-prisma#22]
## Versions
```json
"@prisma/client": "^5.17.0"
"@prisma/nuxt": "^0.0.30"
"nuxt": "^3.12.3",
"prisma": "^5.17.0",
```

## Issue

Running the dev server works fine.
Running `nuxt build` (via `npm run build`) when `@prisma/nuxt` is listed in the modules in `nuxt.config.ts` deletes other nuxt modules from `node_modules/@nuxt`, leading to errors such as:

```
Error while requiring module @nuxt/devtools: Error: Cannot find module '@nuxt/devtools'
```

or '@nuxt/test-utils', etc: the first module that fails to be found depends on the order in which modules are listed in nuxt.config.ts.

Before running `npm run build`, the nuxt part of my node_modules looked like this:

![Screenshot from 2024-07-18 14-54-08](https://github.com/user-attachments/assets/7d5e11de-eb9d-40ab-8029-85de4162795a)

After running `npm run build`, which errored as above, the nuxt part of my node_modules looked like this:

![Screenshot from 2024-07-18 14-53-30](https://github.com/user-attachments/assets/0a58aa8a-731d-492e-8637-747e79df2aa8)

This uninstalled or deleted a lot of nuxt modules, such that for example trying to run `npm run build` immediately afterwards led to:

```bash
npm run build

> build
> nuxt build

sh: 1: nuxt: not found
```

The other modules listed in my `nuxt.config.ts` are:

```ts
modules: [
    "@nuxtjs/fontaine",
    "@pinia/nuxt",
    "@nuxt/test-utils/module",
    "@nuxt/eslint",
    "@nuxtjs/i18n",
  ],
```

## Possible workaround?
My workaround is to not use `@prisma/nuxt`.

I found that I could run the build step and it did not delete nuxt modules, and I could still use prisma (at least, I could perform operations from within an api endpoint, as below) if I uninstalled `@prisma/nuxt`, omitted the module from nuxt.config.ts, and used '[usage option B](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#option-b-libprismats)' instead of the composable.

```ts
import prisma from "~/lib/prisma";

export default defineEventHandler(async (event) => {
  const uniqueString = Math.random().toString(36).substring(7);

  await prisma.user.create({
    data: {
      email: `${uniqueString}@email.com`,
      name: "Hello",
    },
  });

  // Return all users
  return {
    user: await prisma.user.findMany(),
  };
});
```

```
# package.json
...
  "devDependencies": {
    "@antfu/eslint-config": "2.21.0",
    "@nuxt/eslint": "^0.3.13",
    "@nuxt/test-utils": "^3.13.1",
    "@nuxtjs/i18n": "^8.3.1",
    "@playwright/test": "^1.45.1",
    "@prisma/client": "^5.17.0",
    "@types/lodash.throttle": "^4.1.9",
    "@types/node": "^20.14.9",
    "@vitest/coverage-v8": "^1.6.0",
    "@vue/test-utils": "^2.4.6",
    "jsdom": "^24.1.0",
    "lint-staged": "^15.2.7",
    "nuxt": "^3.12.3",
    "prisma": "^5.17.0",
    "sass": "^1.77.6",
    "simple-git-hooks": "^2.11.1",
    "vitest": "^1.6.0"
  },
```

**Comment by Harm-Nullix** [comment]
Same issue, this is so lame :P

https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L85 Also causes optimizeDepths to be totally rewritten.

This Module assumes more things like:
* settings experimental options: https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L74
* exposing use of prisma to the frontend: https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L97

In current state, would not recommend using this module. (sorry for the bash, I know people work hard on this but it just isn't production worthy for my 2cents )

**Comment by BlueBazze** [comment]
> Could you provide a reproduction so I can better investigate the problem?

Im sorry i dont mean to be rude or anything in that direction.
You need a reproduction to see that the module is overriding entire `nuxt.options.vite.optimizeDeps`?
https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L87-L89
If `nuxt.options.vite.optimizeDeps` has any value before this module is set up it will get deleted.
If the user uses this key in their nuxt.config.ts it will get overridden.

You can either run .push or just throw defu at it
```ts
      nuxt.options.vite.optimizeDeps = defu(nuxt.options.vite.optimizeDeps, {
        include: ["@prisma/nuxt > @prisma/client"],
      });
```

The assumption regarding the exposure to the runtimeConfig.
`nuxt.options.runtimeConfig.public.prisma` exposes to the frontend.
`nuxt.options.nitro.runtimeConfig.public.prisma` exposes only to server side.

**Comment by xinconan** [comment]
Same issue. It doesn't seem to have been repaired.

**Comment by nonhana** [comment]
Me too.

**Comment by damisparks** [comment]
@david-mears-2, you are a star ⭐  for opening the issue. It took me a couple of days to figure out what was happening. I can confirm the issue reported. It is quite frustrating 

In the video you will see how the prisma is removed `@damisparks/eslint-config`.

https://github.com/user-attachments/assets/7f9ca5fb-e6b5-40c9-b9b2-732bef4386d1
