### ISSUE TITLE
Package manager cannot get resolved when using Nuxt Layers

### ISSUE THREAD

**Issue by Dobefu** [prisma/nuxt-prisma#29]
This is a continuation of #20. I'll provide a summary of the issue:

When using Nuxt layers and Node/PNPM workspaces, no lockfiles will be present in the directory of the Nuxt layer. This causes nuxt-prisma to fall back to `npm`. This becomes a problem when using `pnpm` and its workspaces functionality, since `npm` has no idea what the heck it should do.

I imagine the solution be twofold:
1. Look at the actual project root for the lockfiles
2. Throw a warning when the package manager falls back to `npm`, since something is not right at that point

I have a reproduction repository here: https://github.com/Dobefu/nuxt-prisma-pnpm-workspaces

Also, I intend to write a fix for this, but I'll have some lunch first.
🥪 <- This is what my lunch will look like

**Comment by ankur-arch** [comment]
Thanks @Dobefu! We should consider closing #31 while working on this.
