### ISSUE TITLE
Failed on initial start (bun)

### ISSUE THREAD

**Issue by unpseudocomplique** [prisma/nuxt-prisma#31]
Hi, thanks for the nuxt module !

I belive this may be linked to the fact that i'm using Bun.

i have this error on the first start after module install : 
<img width="696" alt="image" src="https://github.com/user-attachments/assets/16b51610-a0dc-4671-8839-725fdffbf7fb">

The strange part is that in the error it's written "npx npx". Anyway in bun this should be "bunx": 

`bunx prisma init --datasource-provider postgresql`
Work fine

Maybe https://unjs.io/packages/nypm could help ?

(i have installed node with nvm and desactived it to have the full power of bun with 
nvm deactivate)

**Comment by unpseudocomplique** [comment]
ho sorry  `bunx prisma init --datasource-provider postgresql` did not give me any error but did nothing !

**Comment by ankur-arch** [comment]
>  The strange part is that in the error it's written "npx npx"
Thanks @unpseudocomplique , caught a small bug here 😄 .
https://github.com/prisma/nuxt-prisma/pull/33

> Maybe [unjs.io/packages/nypm](https://unjs.io/packages/nypm) could help ?

This looks interesting 😄 , will take a look at it!

**Comment by Ed1ks** [comment]
Sadly prisma does not run with bun, pnpm, nor yarn.
https://stackblitz.com/edit/nuxt-starter-zgouyq

**Comment by Kuuzoo** [comment]
> Sadly prisma does not run with bun, pnpm, nor yarn. https://stackblitz.com/edit/nuxt-starter-zgouyq

We definitely need to get support for this...

**Comment by ankur-arch** [comment]
Hey @Ed1ks 👋,

`v0.2` is compatible with npm, yarn, and pnpm. However, there’s a known issue with Bun that’s currently being tracked [here](https://github.com/prisma/nuxt-prisma/issues/72).

Hi @unpseudocomplique I appreciate you raising this 🙏 ! Please follow [this](https://github.com/prisma/nuxt-prisma/issues/72) issue for Bun support.
