### ISSUE TITLE
Disabling the Studio prompt in the Nuxt module

### ISSUE THREAD

**Issue by hamzanouali42** [prisma/nuxt-prisma#38]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@prisma/nuxt@0.0.35` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@prisma/nuxt/dist/module.mjs b/node_modules/@prisma/nuxt/dist/module.mjs
index 3e2e941..9246dd2 100644
--- a/node_modules/@prisma/nuxt/dist/module.mjs
+++ b/node_modules/@prisma/nuxt/dist/module.mjs
@@ -540,13 +540,13 @@ const module = defineNuxtModule({
         await installAndStartPrismaStudio();
         return;
       }
-      const promptResults = await executeRequiredPrompts({
+      /* const promptResults = await executeRequiredPrompts({
         promptForMigrate: false,
         promptForPrismaStudio: true
       });
       if (promptResults?.promptForInstallingStudio) {
         await installAndStartPrismaStudio();
-      }
+      } */
     };
     if (!prismaSchemaExists) {
       await prismaInitWorkflow();
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Hello, I disabled this part because it's annoying, every time nuxt needs to restart, it gets blocked by this prompt, please add a configuration option to disable it.

Thank you guys for making this module!! and good luck.

**Comment by jonas9105** [comment]
+1

**Comment by ankur-arch** [comment]
>  You can add this to nuxt.config.ts to stop getting the prompt every time:
prisma: { autoSetupPrisma: true },


Thanks @ipanamski that is the solution to this issue 😄 .
