### ISSUE TITLE
Prisma is not defined in server API

### ISSUE THREAD

**Issue by Corentin7301** [prisma/nuxt-prisma#41]
In the [doc](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#using-the-auto-imported-prisma-client-instance-in-your-api-route), I read: `You can use the auto-imported Prisma Client instance`.

But when I create a API route and I use in my app, I've this error message: `prisma is not defined`...

I don't understand... And so, what can I import for use prisma in my API route?

```ts
// /api/customer.ts
 
export default defineEventHandler(async (event) => {
    return {
      user: await prisma.user.findFirst(),
    };
});
```

```html


<template>
<div>
  <pre>{{ data }}</pre>
</div>
</template>

<script setup>
const { data } = await useFetch('/api/customer')
</script>
```

Thanks for help! 🚀

**Comment by ankur-arch** [comment]
Hey there @Corentin7301 👋 ,

Apologies for the delayed response, I was away on time off. I'll check and get back, this maybe a regression from a release. 
Meanwhile, could you check whether this [approach](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#using-the-global-prisma-client-instance-in-your-api-route) works for you:

```typescript
import prisma from "~/lib/prisma";

export default defineEventHandler(async (event) => {
  return {
    user: await prisma.user.findFirst(),
  };
});
```
