### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier

### ISSUE THREAD

**Issue by mahdi4187** [prisma/nuxt-prisma#45]
`Uncaught TypeError: Failed to resolve module specifier ".prisma/client/index-browser". Relative references must start with either "/", "./", or "../".`

I get error after run in server

Please guide me
```[tasklist]
### Tasks
```

**Comment by ankur-arch** [comment]
Thanks for reporting @mahdi4187 , what version of nuxt are you using? Could this be related to #44

**Comment by toni14nexe** [comment]
@mahdi4187 Try this [suggestion](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module#resolving-typeerror-failed-to-resolve-module-specifier-prismaclientindex-browser), @ankur-arch sent me and it managed to solve the identical problem to me.

**Comment by ankur-arch** [comment]
Thanks @toni14nexe, I think this is a duplicate and am closing this. We'll reopen it if it's not the case.
